config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'landing#index'
  get '/landing' => 'landing#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :conversations
  resources :listings
  resources :profiles
  post 'messages' => 'messages#create'

  get '/followers' => 'followers#index'
  get '/following' => 'following#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id             :integer          not null, primary key
#  first_name     :string
#  last_name      :string
#  date_of_birth  :date
#  city           :string
#  country        :string
#  contact_number :string
#  bio            :text
#  photo_data     :text
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Profile < ApplicationRecord
  include ImageUploader::Attachment.new(:photo)

  # validates :first_name, :last_name, :date_of_birth, :city, :country, presence: true
  # validates :bio, length: {maximum: 400}

  belongs_to :user

  # Full Name (First Name and Last Name)
  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    redirect_to edit_profile_url if @profile.nil?

    @no_trade_owned_products = @profile.user.listings.where(category_id: 'products', status: 'owned', item_type: 'no-trade')
    @no_trade_owned_skills = @profile.user.listings.where(category_id: 'skills', status: 'owned', item_type: 'no-trade')
    @trade_owned_products_or_skills = @profile.user.listings.where(category_id: ['skills', 'products'], status: 'owned', item_type: 'trade')
    @trade_wanted_skills = @profile.user.listings.where(category_id: 'skills', status: 'wanted')
    @trade_wanted_products = @profile.user.listings.where(category_id: 'products', status: 'wanted')

  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find_or_initialize_by(user: current_user)
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :date_of_birth, :city, :country, :contact_number, :bio, :photo, :user_id)
    end

    def performing_follow?
      # Is there a 'toggle_follow' field in the form?
      params.require(:user)[:toggle_follow].present?
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :profile_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :profile_last_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth, start_year: Time.now.year - 100, end_year: Time.now.year, id: :profile_date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :profile_city %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :profile_country %>
  </div>

  <div class="field">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number, id: :profile_contact_number %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :profile_bio %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, id: :profile_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<% @profiles.each do |profile| %>
  <figure style="display: inline-block; width: 32%; height: 500px; overflow: hidden;"> 
    <% if profile.photo_url(:thumb) %> 
      <%= image_tag profile.photo_url(:thumb), style: "width: 100px;" %>
    <% end %>
    <p><%= profile.first_name %> <%= profile.last_name %></p>
    <p>Dob: <%= profile.date_of_birth %></p>
    <p><%= profile.city %> <%= profile.country %></p>
    <p>Mobile: <%= profile.contact_number %></p>
    <p><%= profile.bio %></p>
    <%= link_to 'Show', profile %>
    <%= link_to 'Edit', edit_profile_path(profile) %>
    <%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %>
  </figure>  
<% end %>


<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<section class="row profile_header">
    <div class="col row profile_info">
        <% if @profile.photo_url(:thumb).present? %>
            <div class="col profile_photo" style="<%= style_backgound_image(@profile.photo_url(:thumb)) %>"></div>
        <% else %>
            <div class="col profile_photo" style="<%= style_backgound_image(image_url(@profile.image_url)) unless @profile.image_url.nil? %>"></div>
        <% end %>
        <div class="col profile_name">
            <h1><%= "#{@profile.full_name}" %></h1>
        </div>
    </div>
</section>

<section class="row main">
    <div class="col have">
        <div class="items_block">
            <h3>Things I own</h3>
            <% @no_trade_owned_products.each do |item| %>
            <a href="<%= listing_path(item) %>">
                <div class="row item">
                    <% if item.photo_url(:thumb).present? %>
                        <div class="col item_photo" style="<%= style_backgound_image(item.photo_url(:thumb)) %>"></div>
                    <% else %>
                        <div class="col item_photo" style="<%= style_backgound_image(image_url(item.image_url)) unless item.image_url.nil? %>"></div>
                    <% end %>
                    <div class="col item_description">
                        <h4><%= item.name %></h4>
                    </div>
                </div>
            </a>
            <% end %>
        </div>

        <div class="items_block">
            <h3>Skills/Experiences I am good at</h3>
            <% @no_trade_owned_skills.each do |item| %>
            <a href="<%= listing_path(item) %>">
                <div class="row item">
                    <% if item.photo_url(:thumb).present? %>
                        <div class="col item_photo" style="<%= style_backgound_image(item.photo_url(:thumb)) %>"></div>
                    <% else %>
                        <div class="col item_photo" style="<%= style_backgound_image(image_url(item.image_url)) unless item.image_url.nil? %>"></div>
                    <% end %>
                    <div class="col item_description">
                        <h4><%= item.name %></h4>
                    </div>
                </div>
            </a>
            <% end %>
        </div>

        <div class="items_block">
        <h3>Things/Skills I can provide</h3>
            <% @trade_owned_products_or_skills.each do |item| %>
            <a href="<%= listing_path(item) %>">
                <div class="row item">
                    <% if item.photo_url(:thumb).present? %>
                        <div class="col item_photo" style="<%= style_backgound_image(item.photo_url(:thumb)) %>"></div>
                    <% else %>
                        <div class="col item_photo" style="<%= style_backgound_image(image_url(item.image_url)) unless item.image_url.nil? %>"></div>
                    <% end %>
                    <div class="col item_description">
                        <h4><%= item.name %></h4>
                    </div>
                </div>
            </a>
            <% end %>
        </div>
    </div>

    <div class="col want">
        <div class="items_block">
            <h3>Things I want</h3>
            <% @trade_wanted_products.each do |item| %>
                <a href="<%= listing_path(item) %>">
                    <div class="row item">
                        <% if item.photo_url(:thumb).present? %>
                            <div class="col item_photo" style="<%= style_backgound_image(item.photo_url(:thumb)) %>"></div>
                        <% else %>
                            <div class="col item_photo" style="<%= style_backgound_image(image_url(item.image_url)) unless item.image_url.nil? %>"></div>
                        <% end %>
                        <div class="col item_description">
                            <h4><%= item.name%></h4>
                        </div>
                    </div>
                </a>
            <% end %>
        </div>

        <div class="items_block">
        <h3>Skills I want to learn</h3>
            <% @trade_wanted_skills.each do |item| %>
                <a href="<%= listing_path(item) %>">
                    <div class="row item">
                        <% if item.photo_url(:thumb).present? %>
                            <div class="col item_photo" style="<%= style_backgound_image(item.photo_url(:thumb)) %>"></div>
                        <% else %>
                            <div class="col item_photo" style="<%= style_backgound_image(image_url(item.image_url)) unless item.image_url.nil? %>"></div>
                        <% end %>
                        <div class="col item_description">
                            <h4><%= item.name%></h4>
                        </div>
                    </div>
                </a>
            <% end %>
        </div>
    </div>
</section>