config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'landing#index'
  get '/landing' => 'landing#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :conversations
  resources :listings
  resources :profiles
  post 'messages' => 'messages#create'

  get '/followers' => 'followers#index'
  get '/following' => 'following#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  user_id     :integer
#  price       :decimal(, )
#  photo_data  :text
#  category_id :string
#  item_type   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  status      :integer
#

class Listing < ApplicationRecord
  include ImageUploader::Attachment.new(:photo)

  belongs_to :user

  def self.search(search)
    keyword = search.downcase
    where("lower(name) LIKE ? OR lower(description) LIKE ? OR lower(category_id) LIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%")
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
    if params[:search]
      @listings = Listing.search(params[:search]).where.not(user: current_user).order("created_at DESC")
    else
      @listings = Listing.where.not(user: current_user).order("random()")
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @conversation = Conversation.new
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end
  
  # GET /listings/1/edit
  def edit
  end
  
  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user


    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :user_id, :price, :photo, :category_id, :item_type, :status)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Short title for your new listing" %>
    <%= form.text_field :name, id: :listing_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Description for your new listing" %>
    <%= form.text_area :description, id: :listing_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Price" %>
    <%= form.text_field :price, id: :listing_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, id: :listing_photo, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.select :category_id, ['products', 'skills'], id: :listing_category_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Is this an item you own or want to have?" %>
    <%= form.select :status, ['owned', 'wanted'], id: :listing_status, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Is this an item you own or want to have?" %>
    <%= form.select :item_type, ['trade', 'no-trade'], id: :listing_item_type, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary"%>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%#= link_to 'Show', @listing %>
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<section class="row main">
  <div class="col search-listing">
    <div class="search" style="z-index: 10;">
      <%= form_tag(@listing, method: "get") do %>
        <%= text_field_tag :search, params[:search], placeholder: "What are you looking for?" %>
        <%= submit_tag "Search" %>
      <% end %>
    </div>
  </div>
</section>

<section class="row main">
  <div class="col listing">
      <div class="items_block">
          <% if @listings.count>0 %>
            <h3>Things you may be interested in</h3>
              <% @listings.each do |listing| %>
              <a href="<%= listing_path(listing) %>">
                <div class="d-flex flex-wrap item">
                    <% if listing.photo_url(:thumb).present? %>
                      <div class="p item_photo" style="<%= style_backgound_image(listing.photo_url(:thumb)) %>">
                    <% else %>
                      <div class="p item_photo" style="<%= style_backgound_image(image_url(listing.image_url)) unless listing.image_url.nil? %>"></div>
                    <% end %>
                    <div class="p item_description">
                        <h4><%= listing.name %></h4>
                        <p>
                        <%= listing.description %><br>
                        Posted by <%= listing.user.profile.full_name unless listing.user.profile.nil? %>
                        </p>
                    </div>
                </div>
              </a>
              <% end %>
          <% else %>
            <% if !params[:search].nil? %>
              <h4>There are no listings containing the keyword <%= params[:search] %>.</h4>
            <% else %>
              <h4>There are currently no listings</h4>
            <% end %>
          <% end %>
      </div>

  </div>
</section>


<!-- <p id="notice"><%#= notice %></p> -->

<!-- <h1>Listings</h1> -->


<%# @listings.each do |listing| %>
  <%# if photo_url = listing.user.profile.photo_url(:thumb) %>
  <%#= image_tag photo_url %>
  <%# end %>
  <%#= listing.user.profile.first_name %> <%# listing.user.profile.first_name %>
  <%#= listing.name %>
  <%#= listing.description %>
  <%#= listing.price %>
  <%# if listing.photo_url(:thumb) %>
  <%#= image_tag listing.photo_url(:thumb) %>
  <%# end %>
  <%#= link_to 'Show', listing %>
  <%#= link_to 'Edit', edit_listing_path(listing) %>
  <%#= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%# end %>


  <%#= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<div class="container">
  <h1>New Listing</h1>

  <%= render 'form', listing: @listing %>

  <%= link_to 'Back', listings_path %>
</div>

app/views/listings/show.html.erb
<section class="row main">
    <div class="col d-flex flex-wrap show_item">
        <% if @listing.photo_url(:original) %>
            <div class="p-2 item_image" style="<%= style_backgound_image(@listing.photo_url(:original)) %>"></div>
        <% else %>
            <div class="p-2 item_image" style="background-image: url(<%= image_url(@listing.image_url) unless @listing.image_url.nil? %>);"></div>
        <% end %>
        <div class="p-2 item_info">
            <h4><%= @listing.name %></h4>
            <p>
                <%= @listing.description %>
            </p>
            <div class="show_item_button_group">
                <!-- <button>Message <%#= @listing.user.profile.first_name %></button> -->
                <% if user_signed_in? and @listing.user != current_user %>
                  <%= form_with model: @conversation, local: true do |f| %>
                    <%= f.hidden_field :user_id, value: @listing.user.id %>
                    <%= f.button "Message #{@listing.user.profile.first_name}"  %>
                    <%#= button_tag("Message #{@listing.user.profile.first_name}"), type: 'submit' %>
                  <% end %>
                  <%= link_to button_tag("View #{@listing.user.profile.first_name}'s Profile"), profile_path(@listing.user.profile) %>

                <% elsif user_signed_in? and @listing.user == current_user %>
                    <%= link_to button_tag("Edit"), edit_listing_path(@listing) %>
                    <%= link_to button_tag("Delete"), @listing, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>

                
                <%= link_to button_tag("Close"), listings_path %>
            </div>
        </div>

    </div>
</section>

<%#= link_to 'Edit', edit_listing_path(@listing) %>
<%#= link_to 'Back', listings_path %>