config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'landing#index'
  get '/landing' => 'landing#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :conversations
  resources :listings
  resources :profiles
  post 'messages' => 'messages#create'

  get '/followers' => 'followers#index'
  get '/following' => 'following#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flotsy</title>
    <%= csrf_meta_tags %>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Raleway:300,400" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% unless controller_name == "landing" %>
    <section class="row header">
      <div class="col header_title">
          <a href="<%= listings_path %>"><h1>Flotsy</h1></a>
      </div>
      <div class="col-4 navigation">
          <% if user_signed_in? %> 
            <%= link_to 'My Profile', profile_path(current_user.profile.id) unless current_user.profile.nil? %> | 
            <%= link_to 'New Listing', new_listing_path unless current_user.profile.nil? %> | 
            <%= link_to 'Messages', conversations_path %> | 
            <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
          <% else %>
            <a href="/users/sign_up">Sign Up</a> | 
            <a href="/users/sign_in">Log In</a>
          <% end %>
      </div>
    </section>
    <% end %>

    <% unless controller_name == "landing" %>
    <div class="container">
      <%= yield %>
    </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>